%
% This updates the image generated by plotImage.  It will work with the axis
%  object in obj.guiHandles(2); since this is generally automatically handled,
%  this should be fairly impervious to problems.  
%
function updateImage(obj)
  % --- working image!!
	if (size(obj.workingImage,1) == 0)
		return;
	end

	% --- do we have gui handles
	if (length(obj.guiHandles) == 0)
		return;
	else % --- draw 

 
	  % --- call plotImage
		axes(obj.guiHandles(2));
		cla;
		[imRef axRef figRef] = obj.plotImage(obj.guiShowFlags(1), obj.guiShowFlags(2), ... 
													 obj.guiShowFlags(3), obj.guiSelectedRoiIds, obj.guiHandles(2));
		hold on; % turn hold on
		obj.guiHandles(1) = imRef;
	end

	% --- need to draw gui polygon?
	if (length(obj.guiPolyCorners) > 0)
	  axes(obj.guiHandles(2));
	  hold on;
	  for p=1:size(obj.guiPolyCorners,2) 
		  draw_x(obj.guiPolyCorners(1,p), obj.guiPolyCorners(2,p), 1, [1 0 1]);
			if (p > 1)  
				hold on;
			  plot ([obj.guiPolyCorners(1,p-1) obj.guiPolyCorners(1,p)], ... 
			        [obj.guiPolyCorners(2,p-1) obj.guiPolyCorners(2,p)], '-', ...
							'Color', [1 0 1]); 
			end
		end
	end

	% --- call post-function
	obj.updateImagePostFunction(obj.updateImagePostFunctionParams);
