function [x_p y_p idx] = percentalBinData(x,y,N_bins,percentileLow,percentileHigh)
N_points = length(x);
binSize = ceil(N_points/N_bins);
z(:,1) = x;
z(:,2) = y;
z(:,3) = [1:N_points];
vals   = sortrows(z,1);
x_m = zeros(N_bins,1);
y_m = zeros(N_bins,1);
x_s = zeros(N_bins,1);
y_s = zeros(N_bins,1);
minIdx = floor(percentileLow*binSize);
maxIdx = ceil(percentileHigh*binSize);
minIdx = max([minIdx 1]);
maxIdx = min([maxIdx binSize]);
x_p = [];
y_p = [];
idx = [];
for i=1:N_bins-1,
    aux_x = vals((i-1)*binSize+1:i*binSize,1);
    aux_y = vals((i-1)*binSize+1:i*binSize,2);
    aux_idx = vals((i-1)*binSize+1:i*binSize,3);
    valid_trials = intersect (find(~isnan(aux_x)),find(~isnan(aux_y)));
    clear bin_points
    bin_points(:,1) = aux_x(valid_trials);
    bin_points(:,2) = aux_y(valid_trials);
    bin_points(:,3) = aux_idx(valid_trials);
    orderBin        = sortrows(bin_points,2);
    x_p = [x_p orderBin(minIdx:maxIdx,1)'];
    y_p = [y_p orderBin(minIdx:maxIdx,2)'];
    idx = [idx orderBin(minIdx:maxIdx,3)'];
end
% i=N_bins;
% aux_x = vals((i-1)*binSize+1:end,1);
% aux_y = vals((i-1)*binSize+1:end,2);
% valid_trials = union (~isnan(aux_x),~isnan(aux_y));
% x_m(i) = mean(aux_x(valid_trials ));
% y_m(i) = mean(aux_y(valid_trials ));
% x_s(i) = std(aux_x(valid_trials ))/sqrt(length(valid_trials ));
% y_s(i) = std(aux_y(valid_trials ))/sqrt(length(valid_trials ));    
